CREATE TABLE IF NOT EXISTS "vehicle_listings" (
  "id" serial PRIMARY KEY,
  "reference_number" text NOT NULL UNIQUE,
  "status" text NOT NULL DEFAULT 'pending',
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "phone" text NOT NULL,
  "email" text NOT NULL,
  "city" text NOT NULL,
  "state" text NOT NULL,
  "zip_code" text NOT NULL,
  "is_registered_owner" boolean NOT NULL,
  "year" text NOT NULL,
  "make" text NOT NULL,
  "model" text NOT NULL,
  "trim" text,
  "color" text NOT NULL,
  "vin" text NOT NULL,
  "license_plate" text NOT NULL,
  "mileage" integer NOT NULL,
  "title_status" text NOT NULL,
  "accident_history" text NOT NULL,
  "vehicle_condition" text NOT NULL,
  "has_mechanical_issues" boolean NOT NULL,
  "mechanical_issues_description" text,
  "photo_files" text NOT NULL DEFAULT '',
  "document_files" text NOT NULL DEFAULT '',
  "listing_reason" text NOT NULL,
  "usage_frequency" text NOT NULL,
  "available_days_per_month" text NOT NULL,
  "pickup_location_type" text NOT NULL,
  "street_address" text NOT NULL,
  "location_zip" text NOT NULL,
  "has_gps" boolean NOT NULL DEFAULT false,
  "has_carplay" boolean NOT NULL DEFAULT false,
  "has_android_auto" boolean NOT NULL DEFAULT false,
  "has_backup_camera" boolean NOT NULL DEFAULT false,
  "has_leather_seats" boolean NOT NULL DEFAULT false,
  "has_sunroof" boolean NOT NULL DEFAULT false,
  "has_third_row" boolean NOT NULL DEFAULT false,
  "fleet_interest" text,
  "review_expires_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now()
);
